**EXERCISE**
* Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
* Find the shape, rank and size of the tensors you created in 1.
* Create two tensors containing random values between 0 and 1 with shape [5, 300].
* Multiply the two tensors you created in 3 using matrix multiplication.
* Multiply the two tensors you created in 3 using dot product.
* Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
* Find the min and max values of the tensor you created in 6 along the first axis.
* Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
* Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
* One-hot encode the tensor you created in 9.

In [2]:
import tensorflow as tf

In [7]:
sc = tf.constant(1)
vec = tf.constant([1,2],shape = [2])
mat = tf.constant([[1,2],[3,4]],shape = [2,2])
ten = tf.random.uniform(shape = [2,3,4])
print(sc,vec,mat,ten)

tf.Tensor(1, shape=(), dtype=int32) tf.Tensor([1 2], shape=(2,), dtype=int32) tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) tf.Tensor(
[[[0.95776427 0.9543663  0.31582797 0.2904619 ]
  [0.09933519 0.22072434 0.08343935 0.14647782]
  [0.99482656 0.69357777 0.9515629  0.36173904]]

 [[0.6349226  0.10389173 0.0069896  0.654343  ]
  [0.06649399 0.53303826 0.2643299  0.17381692]
  [0.40748823 0.91674376 0.6863508  0.7131721 ]]], shape=(2, 3, 4), dtype=float32)


In [8]:
print(sc.shape,sc.ndim,tf.size(sc))
print(vec.shape,vec.ndim,tf.size(vec))
print(mat.shape,mat.ndim,tf.size(mat))
print(ten.shape,ten.ndim,tf.size(ten))

() 0 tf.Tensor(1, shape=(), dtype=int32)
(2,) 1 tf.Tensor(2, shape=(), dtype=int32)
(2, 2) 2 tf.Tensor(4, shape=(), dtype=int32)
(2, 3, 4) 3 tf.Tensor(24, shape=(), dtype=int32)


In [10]:
tf.random.set_seed(42)
t1 = tf.random.uniform(shape = [5, 300])
t2 = tf.random.uniform(shape = [5, 300])
print(t1,t2)

tf.Tensor(
[[0.6645621  0.44100678 0.3528825  ... 0.31410468 0.7593535  0.03699052]
 [0.532024   0.29129946 0.10571766 ... 0.54052293 0.31425726 0.2200619 ]
 [0.08404207 0.03614604 0.97732127 ... 0.21516645 0.9786098  0.00726748]
 [0.7396945  0.6653172  0.0787828  ... 0.7117733  0.07013571 0.9409125 ]
 [0.15861344 0.12024033 0.27218235 ... 0.8824879  0.1432488  0.44135118]], shape=(5, 300), dtype=float32) tf.Tensor(
[[0.68789124 0.48447883 0.9309944  ... 0.6920762  0.33180213 0.9212563 ]
 [0.27369928 0.10631859 0.6218617  ... 0.4382149  0.30427706 0.51477313]
 [0.00920248 0.37280262 0.8177401  ... 0.56786287 0.49201214 0.9892651 ]
 [0.88608265 0.08672249 0.12160683 ... 0.91770685 0.72545695 0.8280058 ]
 [0.36690474 0.9200133  0.9646884  ... 0.69012    0.7137332  0.2584542 ]], shape=(5, 300), dtype=float32)


In [15]:
tf.matmul(t1,tf.transpose(t2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33345 , 73.40498 , 77.159615, 73.98369 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.13417 ]],
      dtype=float32)>

In [13]:
tf.tensordot(t1,tf.transpose(t2),axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33345 , 73.40498 , 77.159615, 73.98369 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.13417 ]],
      dtype=float32)>

In [19]:
t3 = tf.random.uniform(shape = [224, 224, 3])
t3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.95831835, 0.01680839, 0.3156035 ],
        [0.16013157, 0.7148702 , 0.7892921 ],
        [0.11484027, 0.33310425, 0.21091413],
        ...,
        [0.6279857 , 0.85051286, 0.9490392 ],
        [0.62438786, 0.2802421 , 0.18754554],
        [0.9087832 , 0.46846092, 0.5317346 ]],

       [[0.85744655, 0.51288927, 0.18603599],
        [0.04882693, 0.78045344, 0.79377043],
        [0.9356363 , 0.32798207, 0.15949786],
        ...,
        [0.6933085 , 0.5420611 , 0.1860913 ],
        [0.7326596 , 0.9234495 , 0.07200372],
        [0.5471792 , 0.24985266, 0.14673471]],

       [[0.5033684 , 0.7000841 , 0.21468806],
        [0.9304948 , 0.17212296, 0.720364  ],
        [0.6657183 , 0.17304075, 0.7110392 ],
        ...,
        [0.35423398, 0.126225  , 0.24436975],
        [0.096439  , 0.06387579, 0.32836854],
        [0.15067935, 0.6084572 , 0.47766674]],

       ...,

       [[0.23573959, 0.42224514, 0.9151635 ],
        [0.38

In [20]:
print(tf.reduce_min(t3,axis = 1))
print(tf.reduce_max(t3,axis = 1))

tf.Tensor(
[[2.36153603e-04 1.92713737e-03 1.57719851e-02]
 [9.43911076e-03 7.83681870e-04 4.70685959e-03]
 [3.52001190e-03 1.21320486e-02 9.85729694e-03]
 [1.21259689e-03 1.13928318e-03 2.14099884e-04]
 [1.09100342e-03 8.64100456e-03 2.10046768e-04]
 [7.13288784e-03 2.82227993e-03 5.58257103e-03]
 [4.43828106e-03 4.89342213e-03 1.29204988e-02]
 [6.13498688e-03 9.18912888e-03 4.88805771e-03]
 [8.91447067e-04 1.10864639e-04 1.43003464e-03]
 [1.84512138e-03 4.87148762e-03 1.11269951e-03]
 [6.07192516e-03 1.42856836e-02 5.65624237e-03]
 [5.76591492e-03 4.08208370e-03 7.58147240e-03]
 [3.12076807e-02 4.29606438e-03 1.60026550e-03]
 [2.74479389e-03 6.42120838e-03 2.82764435e-03]
 [9.80854034e-04 3.78084183e-03 1.50275230e-03]
 [1.33816004e-02 9.48667526e-04 1.15716457e-03]
 [8.27550888e-03 2.33054161e-04 3.00872326e-03]
 [8.71777534e-04 4.14490700e-04 4.94241714e-04]
 [2.56788731e-03 3.37684155e-03 2.52068043e-03]
 [4.45353985e-03 1.67369843e-03 4.08518314e-03]
 [1.50922537e-02 1.07514858e-

In [21]:
t4 = tf.random.uniform(shape = [1, 224, 224, 3])
t4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.43555546, 0.52486527, 0.49674678],
         [0.06710219, 0.35815144, 0.5931845 ],
         [0.8396933 , 0.32720697, 0.08762932],
         ...,
         [0.24612641, 0.9342215 , 0.05903411],
         [0.93307066, 0.512503  , 0.48924422],
         [0.97681785, 0.9894414 , 0.81736803]],

        [[0.9728149 , 0.7123945 , 0.24925625],
         [0.27054942, 0.65331674, 0.25431752],
         [0.29969907, 0.6473402 , 0.61158216],
         ...,
         [0.41850114, 0.9183353 , 0.08774114],
         [0.60710025, 0.92464304, 0.29132044],
         [0.14755595, 0.03294516, 0.8127129 ]],

        [[0.90104914, 0.00804007, 0.2443372 ],
         [0.71701133, 0.90716815, 0.21456563],
         [0.7990829 , 0.9918189 , 0.51183915],
         ...,
         [0.8509488 , 0.8159404 , 0.47705805],
         [0.07570207, 0.73422337, 0.3427385 ],
         [0.26765156, 0.38085854, 0.45572805]],

        ...,

        [[0.18761933, 0.00920856, 

In [22]:
sq_t4 = tf.squeeze(t4)
sq_t4

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.43555546, 0.52486527, 0.49674678],
        [0.06710219, 0.35815144, 0.5931845 ],
        [0.8396933 , 0.32720697, 0.08762932],
        ...,
        [0.24612641, 0.9342215 , 0.05903411],
        [0.93307066, 0.512503  , 0.48924422],
        [0.97681785, 0.9894414 , 0.81736803]],

       [[0.9728149 , 0.7123945 , 0.24925625],
        [0.27054942, 0.65331674, 0.25431752],
        [0.29969907, 0.6473402 , 0.61158216],
        ...,
        [0.41850114, 0.9183353 , 0.08774114],
        [0.60710025, 0.92464304, 0.29132044],
        [0.14755595, 0.03294516, 0.8127129 ]],

       [[0.90104914, 0.00804007, 0.2443372 ],
        [0.71701133, 0.90716815, 0.21456563],
        [0.7990829 , 0.9918189 , 0.51183915],
        ...,
        [0.8509488 , 0.8159404 , 0.47705805],
        [0.07570207, 0.73422337, 0.3427385 ],
        [0.26765156, 0.38085854, 0.45572805]],

       ...,

       [[0.18761933, 0.00920856, 0.70124197],
        [0.08

In [24]:
t5 = tf.random.normal(shape = [10])
t5

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.588346  ,  0.80656034, -0.2999747 , -0.5611263 , -0.05375826,
        0.8035849 ,  0.48094264, -1.3904797 ,  1.5665619 ,  0.5715261 ],
      dtype=float32)>

In [25]:
print(tf.argmin(t5))
print(tf.argmax(t5))

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)


In [32]:
tf.one_hot(tf.cast(t5,dtype = tf.int32),depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>