* tensors
* manipulating tensors
* tensors and numpy
* using @tf.function(a way to speed up regular python func)
* using gpus with tf
* exercise

Tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [2]:
#create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
#create vector
vector = tf.constant([10,19])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 19], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
#create a matrix
m = tf.constant([[10,7],
 [7,0]])
m

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7,  0]], dtype=int32)>

In [7]:
m.ndim

2

In [8]:
m2 = tf.constant([[10.,2.],[2.,2.],[2.,2.]],dtype = tf.float16)
m2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  2.],
       [ 2.,  2.],
       [ 2.,  2.]], dtype=float16)>

In [9]:
m2.ndim

2

In [10]:
#create a tensor
tensor = tf.constant([[[1,2],[2,4]],[[2,3],[2,4]],[[2,3],[2,3]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 4]],

       [[2, 3],
        [2, 4]],

       [[2, 3],
        [2, 3]]], dtype=int32)>

In [11]:
tensor.ndim

3

Creating tensors with tf.Variable

In [12]:
changeable_tensors = tf.Variable([10,7])
unchangeable_tensors = tf.constant([10,7])
changeable_tensors,unchangeable_tensors

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

use .assign() to change a value in tensor

In [13]:
#change in changable
#changeable_tensors[0] = 7 wrong
changeable_tensors[0].assign(7)
changeable_tensors

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
#change in unchangable tensor
#unchangeable_tensors[0].assign(7)
#cant change it.

Creating Random Tensors
tensors of arbitary size containing random nos

In [15]:
r1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
r1 = r1.normal(shape = (3,2,3))
r1

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193765, -1.8107855 ]],

       [[ 0.09988727, -0.50998646, -0.7535806 ],
        [-0.5716629 ,  0.1480774 , -0.23362991]],

       [[-0.3522796 ,  0.40621266, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.44629744]]], dtype=float32)>

In [16]:
r2 = tf.random.Generator.from_seed(42)
r2 = r2.normal(shape = (3,2,3))
r2

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193765, -1.8107855 ]],

       [[ 0.09988727, -0.50998646, -0.7535806 ],
        [-0.5716629 ,  0.1480774 , -0.23362991]],

       [[-0.3522796 ,  0.40621266, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.44629744]]], dtype=float32)>

In [17]:
r1 == r2

<tf.Tensor: shape=(3, 2, 3), dtype=bool, numpy=
array([[[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])>

#shuffle order of elements in a tensor
* change order so that inherent data doesn't effect learning

In [18]:
not_shuff = tf.constant([[10,7],
                         [3,50],
                          [3,7]])
not_shuff.ndim

2

In [19]:
not_shuff

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3, 50],
       [ 3,  7]], dtype=int32)>

In [20]:
tf.random.set_seed(42)
shuff = tf.random.shuffle(not_shuff,seed =42)
shuff

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3, 50],
       [ 3,  7]], dtype=int32)>

In [21]:
tf.random.set_seed(42) #-> global level seed
shuff = tf.random.shuffle(not_shuff,seed =40) #->operational level seed
shuff

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  7],
       [10,  7],
       [ 3, 50]], dtype=int32)>

In [22]:
tf.random.set_seed(1234)
t1 = tf.random.Generator.from_seed(1234)
t1 = t1.normal(shape=(2,3))
t1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.9356609 ,  1.0854306 , -0.93788373],
       [-0.5061547 ,  1.3169702 ,  0.7137579 ]], dtype=float32)>

In [23]:
tf.random.set_seed(1234)
t2 = tf.random.shuffle(t1,seed =42)
t2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.5061547 ,  1.3169702 ,  0.7137579 ],
       [ 0.9356609 ,  1.0854306 , -0.93788373]], dtype=float32)>

global level seed & operational level seed is entered the shuffle DN change meanwhile if -
* gls missing or ols missing - values will start from certain set and will follow it everytime you kill it and re-run it.

In [24]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuff)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3, 50],
       [ 3,  7],
       [10,  7]], dtype=int32)>

Other ways to make tensor


In [25]:
#tensors with all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [26]:
#tensors with all zeroes
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

#turn numpy arrays to tensors

In [27]:
import numpy as np
arr = np.arange(1,25,dtype = np.int32) #create a Numpy array b/w 1 and 25
#X = tf.constant(some_matrix) # capital for matrix or tensors
#y = tf.constant(vector) # non-capital for vector

In [28]:
A =tf.constant(arr,shape = (8,3))
B =tf.constant(arr)
A,B

(<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [29]:
A.ndim,B.ndim

(2, 1)

Getting information from tensors
* shape - tensor.shape
* rank - tensor.ndim
* axis or dimensions - tensor[0],tensor [:,1]
* size - tf.size(tensor)

In [30]:
r4_tensor = tf.zeros([2,3,4,5])

In [31]:
print(r4_tensor.shape)
print(r4_tensor.ndim)
print(tf.size(r4_tensor))

(2, 3, 4, 5)
4
tf.Tensor(120, shape=(), dtype=int32)


In [32]:
#get various attributes of tensor
print("Datatype:",r4_tensor.dtype)
print("No of dimensions (rank)",r4_tensor.ndim)
print("Shape of tensor",r4_tensor.shape)
print("Elements along the 0 axis",r4_tensor.shape[0])
print("Elements along the last axis",r4_tensor.shape[-1])
print("Total no of elements in tensor",tf.size(r4_tensor))

Datatype: <dtype: 'float32'>
No of dimensions (rank) 4
Shape of tensor (2, 3, 4, 5)
Elements along the 0 axis 2
Elements along the last axis 5
Total no of elements in tensor tf.Tensor(120, shape=(), dtype=int32)


Indexing tensors:-just like python list

In [33]:
my_list = [1,2,3,4]
my_list[:2],my_list[:1]

([1, 2], [1])

In [34]:
r4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [35]:
#get first element from each dimension from each index except for final one
r4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
r4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [37]:
#create 2-d tensor
r2 = tf.constant([[1,2],[3,4]])
r_2 = tf.random.Generator.from_seed(42)
r_2 = r_2.normal(shape=(2,2)) # Assuming you want to generate random numbers
print(r2)
print(r_2)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]], shape=(2, 2), dtype=float32)


In [38]:
#last item of each row:-
r2[:,-1:]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [4]], dtype=int32)>

In [39]:
r3 = r2[...,tf.newaxis]
r3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [40]:
#alternate to tf.newaxis
tf.expand_dims(r2,axis = 1) # expand 1-axis
r2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [41]:
tf.expand_dims(r_2,axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ]]], dtype=float32)>

In [42]:
tf.expand_dims(r_2,axis = -1) # means expand final axis

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702]],

       [[ 0.07595026],
        [-1.2573844 ]]], dtype=float32)>

Manipulating tensors (tensor operations)


In [43]:
# +:-
t = tf.constant([[10,7],[4,3]])
t+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [14, 13]], dtype=int32)>

In [44]:
print(t)
t = t+10
print(t)

tf.Tensor(
[[10  7]
 [ 4  3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[20 17]
 [14 13]], shape=(2, 2), dtype=int32)


In [45]:
# - , * , / :-
t = t - 10
print(t)
t = t*10
print(t)
t = t/10
print(t)

tf.Tensor(
[[10  7]
 [ 4  3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 40  30]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10.  7.]
 [ 4.  3.]], shape=(2, 2), dtype=float64)


In [46]:
#We can use tf built -in func:-
tf.multiply(t,10)
print(t)

tf.Tensor(
[[10.  7.]
 [ 4.  3.]], shape=(2, 2), dtype=float64)


In [47]:
tf.add(t,10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[20., 17.],
       [14., 13.]])>

In [48]:
#tf.div(t,10)
#tf.sub(t,10)
#Does not exist

Matrix multiplication:-
* use tf.linalg library :- tf.matmul(t1,t2)
* use @ (python matrix mult operator)
* use tf.tensordot(t1,t2,axes,name)

In [49]:
tensor1 = tf.random.normal(shape = (3,2))
tensor2 = tf.random.normal(shape = (2,3))
tensor1,tensor2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.08422458, -0.86090374],
        [ 0.37812304, -0.00519627],
        [-0.49453196,  0.6178192 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.5590974 , -0.5347214 ,  2.3730333 ],
        [-1.5725931 ,  0.80550563, -0.83387697]], dtype=float32)>)

In [50]:
tf.matmul(tensor1,tensor2)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.3067616 , -0.73849946,  0.91775554],
       [-0.203236  , -0.2063761 ,  0.90163165],
       [-0.69508666,  0.76209366, -1.688726  ]], dtype=float32)>

In [51]:
t1 = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
t2 = tf.constant([[3,5],[6,7],[1,8]])
tf.matmul(t1,t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [52]:
t1@t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [53]:
#create a tensor (3,2,3) tensor and (2,3,1) tensor
tf1 = tf.random.normal(shape = (3,2,3))
tf2 = tf.random.normal(shape = (2,3,1))
tf.matmul(tf1,tf2)

InvalidArgumentError: {{function_node __wrapped__BatchMatMulV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} In[0] and In[1] must have compatible batch dimensions: [3,2,3] vs. [2,3,1] [Op:BatchMatMulV2] name: 

In [54]:
#tensor of same shape
tf1 = tf.random.normal(shape = (3,2,3))
tf2 = tf.random.normal(shape = (3,2,3))
tf.matmul(tf1,tf2)


InvalidArgumentError: {{function_node __wrapped__BatchMatMulV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} Matrix size-incompatible: In[0]: [3,2,3], In[1]: [3,2,3] [Op:BatchMatMulV2] name: 

rules:-
* the inner dimensions must match
* resulting matrix must have same shape of outer dimensions

In [55]:
#transpose
tf1,tf.transpose(tf1)

(<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
 array([[[ 0.0307604 ,  0.29017973,  1.2829775 ],
         [ 0.81271535, -0.7944917 ,  0.20022835]],
 
        [[ 1.80325   , -1.0376493 , -1.2340679 ],
         [-1.2608271 ,  0.11458235,  0.11852823]],
 
        [[-1.2859143 ,  1.2248926 ,  2.7304003 ],
         [ 0.55216455, -0.8338689 , -0.21482149]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
 array([[[ 0.0307604 ,  1.80325   , -1.2859143 ],
         [ 0.81271535, -1.2608271 ,  0.55216455]],
 
        [[ 0.29017973, -1.0376493 ,  1.2248926 ],
         [-0.7944917 ,  0.11458235, -0.8338689 ]],
 
        [[ 1.2829775 , -1.2340679 ,  2.7304003 ],
         [ 0.20022835,  0.11852823, -0.21482149]]], dtype=float32)>)

In [56]:
X = tf.random.normal(shape = (3,2))
Y = tf.random.normal(shape = (3,2))
Z = tf.tensordot(X,tf.transpose(Y),axes = 1)
W = tf.tensordot(X,tf.reshape(Y,shape = (2,3)),axes = 1)
comparison_result = tf.reduce_all(tf.equal(Z, W))
if(comparison_result):
  print("True")
else:
  print("false")


false


In [57]:
print("Y",Y)
print("transpose:",tf.transpose(Y))
print("reshape:",tf.reshape(Y,shape = (2,3)))

Y tf.Tensor(
[[-1.5883462   0.8065604 ]
 [-0.2999747  -0.5611263 ]
 [-0.05375826  0.8035849 ]], shape=(3, 2), dtype=float32)
transpose: tf.Tensor(
[[-1.5883462  -0.2999747  -0.05375826]
 [ 0.8065604  -0.5611263   0.8035849 ]], shape=(2, 3), dtype=float32)
reshape: tf.Tensor(
[[-1.5883462   0.8065604  -0.2999747 ]
 [-0.5611263  -0.05375826  0.8035849 ]], shape=(2, 3), dtype=float32)


Use transpose instead of reshape


# **CHANGE DATATYPE OF TENSOR**
* use tf.cast(t1,dtype = int16/float16)

In [58]:
B = tf.constant([1.7,1.4])
B.dtype

tf.float32

In [59]:
C = tf.constant([17,14])
C.dtype

tf.int32

In [60]:
#change float32 to float16 (reducing precision)
d = tf.cast(B,dtype = tf.float16)
d,d.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 1.4], dtype=float16)>,
 tf.float16)

In [61]:
c = tf.cast(C,dtype = tf.int16)
c

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([17, 14], dtype=int16)>

# **Aggregating tensors**
* condensing tensor to smaller no of values

In [62]:
#get the absolute
D = tf.constant([-7,-10])
D = tf.abs(D)

* get the min
* get the max
* get the mean
* get the sum
*

In [63]:
# create a random tensor with values b/w 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([86, 14, 34, 26, 47, 10, 42, 16, 16, 39, 32, 57, 74, 10,  1, 48, 98,
       64, 85, 95, 12, 98, 64, 22, 33, 80, 21, 80, 86, 96, 19, 48, 56, 14,
       40, 28, 15, 55, 16, 58, 75, 46,  0, 91, 14, 81, 90, 57, 38, 44])>

In [64]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [65]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [66]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [67]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2371>

In [68]:
variance = tf.math.reduce_variance(tf.cast(E, tf.float32)) # Cast to float32 for variance calculation
print("Variance:", variance.numpy())

std_dev = tf.math.reduce_std(tf.cast(E, tf.float32)) # Cast to float32 for std_dev calculation
print("Standard Deviation:", std_dev.numpy())

Variance: 864.6036
Standard Deviation: 29.404142


In [69]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=864>

# Positional maximum and minimum

In [70]:
#create a new tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [71]:
#find positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [72]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [73]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [74]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [75]:
#find positional min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [76]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [77]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [78]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# Squeezing a tensor
* use tf.squeeze(t1):- removes all dimensions of size 1

In [79]:
#create a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]),shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [80]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [81]:
G_squeezed = tf.squeeze(G)
print("tensor:",G_squeezed)
print("shape:",G_squeezed.shape)

tensor: tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
 0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
 0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
 0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
 0.7381023  0.32054043], shape=(50,), dtype=float32)
shape: (50,)


# One hot encoding tensors
* use tf.one_hot(t1,depth)where depth = length or no of values to be encoded

In [82]:
#create a list of indices
some_list = [0,1,2,3] #could be red,green,blue,yellow

#one - hot encoding our list
tf.one_hot(some_list,depth = 4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [83]:
#specify custom values for one hot encoding
tf.one_hot(some_list,depth = 4,on_value = "gud",off_value = "not gud")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'gud', b'not gud', b'not gud', b'not gud'],
       [b'not gud', b'gud', b'not gud', b'not gud'],
       [b'not gud', b'not gud', b'gud', b'not gud'],
       [b'not gud', b'not gud', b'not gud', b'gud']], dtype=object)>

Squaring,log,square root

In [84]:
#create
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [85]:
#Square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [86]:
#sq_root
tf.sqrt(tf.cast(H,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [87]:
#log
tf.math.log(tf.cast(H,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

Tensors and Numpy compatibility
use tensorflow's tensor for faster processing coz the precision diff ie float32 and float64 respectively.

In [88]:
n = np.arange(1,25)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [89]:
N = tf.constant(n,shape = (4,6))
N

<tf.Tensor: shape=(4, 6), dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])>

In [90]:
l = np.array(N)
l

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [91]:
l = N.numpy()
l,type(l)

(array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]),
 numpy.ndarray)

In [92]:
#default dtypes of each are slightly different
numpy_J = tf.constant(np.array([7.,10.,2.]))
tensor_J = tf.constant([7.,10.,2.])
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

# Finding access to GPU's

In [93]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [94]:
!nvidia-smi

Sun Dec 22 16:46:39 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P0              29W /  70W |    117MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--